source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftySurrogate_Example', :exclusive => true do
  pod "SwiftySurrogate", :path => "../"
end

target 'SwiftySurrogate_Tests', :exclusive => true do
  pod "SwiftySurrogate", :path => "../"

  # If you're using Xcode 7 / Swift 2
  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'

  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
